import mongoose from "mongoose";

const projectSchema = new mongoose.Schema(
  {
    seller: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    title: {
      type: String,
      required: [true, "Project title is required"],
      trim: true,
      minlength: [5, "Title must be at least 5 characters"],
      maxlength: [100, "Title cannot exceed 100 characters"],
    },
    description: {
      type: String,
      required: [true, "Project description is required"],
      minlength: [10, "Description must be at least 10 characters"],
      maxlength: [500, "Description cannot exceed 500 characters"],
    },
    readme: {
      type: String,
      required: [true, "README is required"],
    },
    category: {
      type: String,
      required: true,
      enum: ["trending", "hackathon", "last-minute", "all"],
      default: "all",
    },
    badge: {
      type: String,
      required: true,
      enum: ["silver", "gold", "diamond"],
      default: "silver",
    },
    price: {
      type: Number,
      required: [true, "Price is required"],
      min: [0, "Price cannot be negative"],
    },
    techStack: {
      type: [String],
      required: true,
    },
    // AI Context Files (stored as text in MongoDB)
    folderStructure: {
      type: String,
      default: "",
    },
    codeFiles: [
      {
        filename: { type: String, required: true },
        path: { type: String, required: true },
        content: { type: String, required: true },
        language: { type: String, required: true },
        isContextFile: { type: Boolean, default: true },
        isMain: { type: Boolean, default: false },
      },
    ],
    // Milestones (generated by AI)
    milestones: [
      {
        number: { type: Number, required: true },
        title: { type: String, required: true },
        description: { type: String },
        estimatedTime: { type: String, default: "2 hours" },
        steps: [
          {
            stepNumber: { type: Number, required: true },
            title: { type: String, required: true },
            description: { type: String },
            instructions: { type: String },
            codeBlocks: [
              {
                fileName: { type: String },
                language: { type: String },
                code: { type: String },
              },
            ],
            verificationSteps: { type: String },
            hints: { type: String },
          },
        ],
        quiz: {
          questions: [
            {
              question: { type: String },
              options: [{ type: String }],
              correctAnswer: { type: Number },
              explanation: { type: String },
            },
          ],
        },
      },
    ],
    // Trial Settings
    trialSettings: {
      isTrialAvailable: { type: Boolean, default: true },
      trialMilestones: { type: Number, default: 1 }, // Number of free milestones
    },
    // Download Links (full project)
    downloadLink: {
      type: String,
      required: [true, "Download link is required"],
    },
    githubUrl: String,
    googleDriveUrl: String,
    // Media
    screenshots: [String],
    thumbnail: {
      public_id: String,
      secure_url: String,
    },
    // Metadata
    views: { type: Number, default: 0 },
    purchases: { type: Number, default: 0 },
    rating: { type: Number, default: 0, min: 0, max: 5 },
    reviews: [
      {
        user: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        rating: { type: Number, required: true },
        comment: { type: String },
        createdAt: { type: Date, default: Date.now },
      },
    ],
    isPublished: { type: Boolean, default: false },
    // Review System
    reviewStatus: {
      type: String,
      enum: ["draft", "pending", "approved", "rejected", "needs-changes"],
      default: "draft",
    },
    adminNotes: { type: String, default: "" },
    submittedAt: { type: Date },
    complexity: {
      type: String,
      enum: ["simple", "intermediate", "complex"],
      default: "intermediate",
    },
  },
  { timestamps: true }
);

// Indexes for better query performance
projectSchema.index({ category: 1, badge: 1 });
projectSchema.index({ techStack: 1 });
projectSchema.index({ seller: 1 });
projectSchema.index({ isPublished: 1 });

const Project = mongoose.model("Project", projectSchema);

export default Project;
